### ISSUE TITLE
Extension is 'tricked' into thinking NASM is installed

### ISSUE THREAD

**Issue by lw-lonewolf** [NotTahaAli/NASM-Tools#26]
In certain cases (e.g. uninstallation of NASM after the extension is set up) the extension believes NASM is installed although it isn't. 

## Steps to Recreate
* Install Extension 
* Install NASM and enable extension 
* Close VS Code
* Uninstall NASM
* Reopen VS Code

**Comment by lw-lonewolf** [comment]
Resolved in #24

**Comment by NotTahaAli** [comment]
Introduction of !commandExists.sync('nasm') and !commandExists.sync('dosbox') introduces the following issues
- The NASM and DOSBox commands are config variables as they can be changed. However introduction of these lines make them static
- in the Winget installation, NASM is not added to path
- The Program should support dosbox-x as well as dosbox as package installation of dosbox is broken on windows systems due to source forge repo not working.
